services:
  postgres:
    image: postgres:15
    container_name: getir-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: library_system_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d library_system_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: getir-app
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/library_system_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    command: ["java", "-jar", "app.jar"]

volumes:
  pgdata: